project_id = "default"

[functions]
# Configurações para Edge Functions

[functions.env_vars]
# Estas variáveis serão carregadas do arquivo .env da raiz do projeto
# As Edge Functions do Supabase irão usar os valores definidos no .env principal
