project_id = "default"

[functions]
# Configurações para Edge Functions

[functions.env_vars]
OPENAI_API_KEY = "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"
SUPABASE_URL = "https://supabase.cirurgia.com.br"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UtZGVtbyIsCiAgICAiaWF0IjogMTY0MTc2OTIwMCwKICAgICJleHAiOiAxNzk5NTM1NjAwCn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJzZXJ2aWNlX3JvbGUiLAogICAgImlzcyI6ICJzdXBhYmFzZS1kZW1vIiwKICAgICJpYXQiOiAxNjQxNzY5MjAwLAogICAgImV4cCI6IDE3OTk1MzU2MDAKfQ.DaYlNEoUrrEn2Ig7tqibS-PHK5vgusbcbo7X36XVt4Q"
