// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gyhklifdpebujlvgwldi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5aGtsaWZkcGVidWpsdmd3bGRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MTkxMTksImV4cCI6MjA2MTM5NTExOX0.dbdpX-2Ae5ffMVOvgbllouYQuYg7XOksSM4SqCTTzIk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);