// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js'

// Pega a URL e a chave anônima do Supabase das variáveis de ambiente
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY

// Validação para garantir que as variáveis de ambiente foram carregadas
if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error("Supabase URL or Anon Key is missing. Make sure you have VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY set in your .env file.")
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey)